updated meteo_access functions to include WCC, began draft for gpm access
LynkerIntel/rainOrSnowTools pull request #1
Opened 2023-07-11 21:43 UTC by nayhur

2023-07-25 18:35 UTC, SnowHydrology requested changes
@nayhur, thanks for getting this started! Can you address the changes I suggested for the ecoregion and state functions? After those are integrated, I can get started on the met access function for WCC. Thank you!

2023-07-25 18:35 UTC, SnowHydrology commented on R/citsci_preprocess.R
> +  locs = sf::st_as_sf(data.frame(lon_obs, lat_obs),
@nayhur, please add the `sf` package to the list of `Imports` in the `DESCRIPTION` file in the main level of the repo (https://github.com/SnowHydrology/rainOrSnowTools/blob/e81ad1d3d7913f702d3fbce8a40c3ba793e71895/DESCRIPTION#L13).

2023-07-25 18:35 UTC, SnowHydrology commented on R/citsci_preprocess.R
> +get_geoinfo <- function(lon_obs, lat_obs){
@nayhur, let's split this into 3 functions:

- `get_eco_level3`
- `get_eco_level4`
- `get_state`

Or conversely, you could keep the generic `get_geoinfo` function and have the type of data (ecoregion level vs. state) be an argument to the function. We only want this function to return a single value or column of values at a time.

2023-07-25 18:35 UTC, SnowHydrology commented on data-raw/misc_metadata.R
@nayhur, please delete this file and add a new one called `geographic_metadata.R`. 

We'll want to use the following code from @mikejohnson51 to get ecoregion level 4 data:

```
library(glue)
library(rmapshaper)
library(sf)

################################################################################
# Script for ecoregion and state data
################################################################################

get_ecoregion = function(level = 4){
  
  temp = tempfile()
  eco = tempfile()
  
  URL = glue("[https://gaftp.epa.gov/EPADataCommons/ORD/Ecoregions/us/us_eco_l{level}_state_boundaries.zip](https://gaftp.epa.gov/EPADataCommons/ORD/Ecoregions/us/us_eco_l%7Blevel%7D_state_boundaries.zip)")
  
  download.file(URL, temp)
  
  # Unzip the contents of the temp and save unzipped contents in 'eco'
  unzip(zipfile = temp, exdir = eco)
  
  # Read the shapefile
  sf::read_sf(eco) %>%
    st_make_valid() %>% 
    ms_simplify(keep_shapes = TRUE) %>% 
    st_transform(crs = 4326) 
}

ecoregions_states = get_ecoregion(4)
usethis::use_data(ecoregions_states, overwrite = TRUE)
```

2023-07-25 18:35 UTC, SnowHydrology commented on R/sysdata.rda
@nayhur, please update the geographic metadata per my other comment. Once that's done, rerun `meteo_metadata.R` to update `sysdata.rda`.

2023-07-25 18:35 UTC, SnowHydrology commented on data-raw/misc_metadata.R
And once the code is updated, we'll add another R file to the `R` directory that includes this text:

```
#' Ecoregions Levels 2, 3, and 4 plus US State Boundaries

"ecoregions_states"
```

2023-07-25 18:38 UTC, mikejohnson51 commented on R/sysdata.rda
If using the above approach and documented dataset, the outputs will go into `data` and `sysdata.rda` should be deleted. If you want to keep `sysdata.rds` then add `intern = TRUE` to `use_data()` and dont add the new data documentation R file. Happy to help if needed!

2023-07-26 13:03 UTC, SnowHydrology commented on R/sysdata.rda
@mikejohnson51, we'll continue to use `sysdata.rda` for the met network metadata.

2023-07-31 22:16 UTC, nayhur commented on data-raw/misc_metadata.R
Does it matter what the file name is?

2023-11-13 17:37 UTC, closed without merging